"use client";
import { useEffect, useMemo, useReducer, useRef, useState } from "react";
import type { KeyboardEvent } from "react";
import type { KeyPair } from "@pqc-sdk/core";

type Algorithm = "ml-kem-768" | "x-wing";
type Phase = "idle" | "generating" | "encrypting" | "decrypting";
type KemPair = KeyPair<"ml-kem-768" | "x-wing">;
type TraceEvent = {label:string; detail:string; time:number; tone:"accent"|"success"};
type State = { message:string; algorithm:Algorithm; pair:KemPair|null; ciphertext:Uint8Array|null; plaintext:string|null; plaintextSize:number|null; verified:boolean; times:{key:number|null;encrypt:number|null;decrypt:number|null}; phase:Phase; error:string|null; trace:TraceEvent[] };
type Action = {type:"message";value:string}|{type:"algorithm";value:Algorithm}|{type:"phase";value:Phase}|{type:"keys";pair:State["pair"];duration:number;elapsed:number}|{type:"encrypted";value:Uint8Array;duration:number;elapsed:number}|{type:"decrypted";value:string;plaintextSize:number;duration:number;elapsed:number;verified:boolean}|{type:"error";value:string};
const initial:State={message:"This message should remain private.",algorithm:"ml-kem-768",pair:null,ciphertext:null,plaintext:null,plaintextSize:null,verified:false,times:{key:null,encrypt:null,decrypt:null},phase:"idle",error:null,trace:[]};
function reducer(s:State,a:Action):State{switch(a.type){case"message":return{...s,message:a.value,pair:null,ciphertext:null,plaintext:null,plaintextSize:null,verified:false,times:{key:null,encrypt:null,decrypt:null},error:null,trace:[]};case"algorithm":return{...initial, message:s.message,algorithm:a.value};case"phase":return{...s,phase:a.value,error:null};case"keys":return{...s,pair:a.pair,phase:"idle",ciphertext:null,plaintext:null,plaintextSize:null,verified:false,times:{key:a.duration,encrypt:null,decrypt:null},error:null,trace:[{label:"Key pair generated",detail:"Post-quantum key pair ready",time:a.elapsed,tone:"accent"}]};case"encrypted":return{...s,ciphertext:a.value,phase:"idle",plaintext:null,plaintextSize:null,verified:false,times:{...s.times,encrypt:a.duration,decrypt:null},error:null,trace:[...s.trace,{label:"Message encrypted",detail:"Ciphertext sealed with the public key",time:a.elapsed,tone:"accent"}]};case"decrypted":return{...s,plaintext:a.value,plaintextSize:a.plaintextSize,verified:a.verified,phase:"idle",times:{...s.times,decrypt:a.duration},error:null,trace:[...s.trace,{label:"Message decrypted",detail:"Plaintext returned",time:a.elapsed,tone:"accent"},...(a.verified?[{label:"Verification successful",detail:"Plaintext matches the original message",time:a.elapsed,tone:"success" as const}]:[])]};case"error":return{...s,phase:"idle",pair:null,ciphertext:null,plaintext:null,plaintextSize:null,verified:false,times:{key:null,encrypt:null,decrypt:null},error:a.value,trace:[]}}}
const ms=(n:number|null)=>n===null?"Waiting":`${n.toFixed(1)} ms`;
const code=`import { pqc } from '@pqc-sdk/core';

const pair = await pqc.keys.generate();

const ciphertext = await pqc.encrypt(
  message,
  pair.publicKey
);

const plaintext = await pqc.decrypt(
  ciphertext,
  pair.secretKey
);`;
async function generatePair(pqc: typeof import("@pqc-sdk/core").pqc, algorithm: Algorithm): Promise<KemPair> {
  return algorithm === "x-wing" ? pqc.keys.generate({ algorithm: "x-wing" }) : pqc.keys.generate({ algorithm: "ml-kem-768" });
}

export function Demo(){
 const [s,d]=useReducer(reducer,initial); const [copied,setCopied]=useState(false); const [copyError,setCopyError]=useState(false); const [installTab,setInstallTab]=useState<"pnpm"|"npm"|"yarn">("npm"); const operationLock=useRef(false); const executionSnapshot=useRef<string|null>(null); const installTabsRef=useRef<HTMLDivElement>(null);
 const busy=s.phase!=="idle"; const total=useMemo(()=>Object.values(s.times).reduce<number>((a,b)=>a+(b??0),0),[s.times]); const max=Math.max(...Object.values(s.times).map(x=>x??0),1);
 function beginOperation(){if(operationLock.current)return false;operationLock.current=true;return true}
 async function generateKeys(pqc:typeof import("@pqc-sdk/core").pqc,algorithm:Algorithm,traceStart:number){d({type:"phase",value:"generating"});const t=performance.now();const pair=await generatePair(pqc,algorithm);const now=performance.now();d({type:"keys",pair,duration:now-t,elapsed:now-traceStart});return pair}
 async function encryptMessage(pqc:typeof import("@pqc-sdk/core").pqc,message:string,pair:KemPair,traceStart:number){d({type:"phase",value:"encrypting"});const t=performance.now();const value=await pqc.encrypt(message,pair.publicKey);const now=performance.now();d({type:"encrypted",value,duration:now-t,elapsed:now-traceStart});return value}
 async function decryptMessage(pqc:typeof import("@pqc-sdk/core").pqc,ciphertext:Uint8Array,pair:KemPair,messageSnapshot:string|null,traceStart:number){d({type:"phase",value:"decrypting"});const t=performance.now();const value=await pqc.decrypt(ciphertext,pair.secretKey);const now=performance.now();const plaintext=new TextDecoder().decode(value);d({type:"decrypted",value:plaintext,plaintextSize:value.byteLength,duration:now-t,elapsed:now-traceStart,verified:messageSnapshot!==null&&plaintext===messageSnapshot});return plaintext}
 async function generate(){if(!beginOperation())return;executionSnapshot.current=null;try{const {pqc}=await import("@pqc-sdk/core");await generateKeys(pqc,s.algorithm,performance.now())}catch{d({type:"error",value:"The cryptographic module could not initialize. Try a current browser and run again."})}finally{operationLock.current=false}}
 async function encrypt(){if(!s.pair||!s.message.trim())return d({type:"error",value:"Enter a message before encrypting."});if(!beginOperation())return;const message=s.message;executionSnapshot.current=message;try{const {pqc}=await import("@pqc-sdk/core");await encryptMessage(pqc,message,s.pair,performance.now())}catch{d({type:"error",value:"Encryption failed. Reset the demo and try again."})}finally{operationLock.current=false}}
 async function decrypt(){if(!s.pair||!s.ciphertext||!beginOperation())return;try{const {pqc}=await import("@pqc-sdk/core");await decryptMessage(pqc,s.ciphertext,s.pair,executionSnapshot.current,performance.now())}catch{d({type:"error",value:"Decryption failed. Reset the demo and try again."})}finally{operationLock.current=false}}
 async function runComplete(){const message=s.message;const algorithm=s.algorithm;if(!message.trim())return d({type:"error",value:"Enter a message before running the demo."});if(!beginOperation())return;executionSnapshot.current=message;const traceStart=performance.now();try{const {pqc}=await import("@pqc-sdk/core");const pair=await generateKeys(pqc,algorithm,traceStart);const ciphertext=await encryptMessage(pqc,message,pair,traceStart);await decryptMessage(pqc,ciphertext,pair,message,traceStart)}catch{d({type:"error",value:"The demo could not complete. Reset it and try again."})}finally{operationLock.current=false}}
 async function copy(text:string){try{if(!navigator.clipboard)throw new Error("Clipboard API unavailable");await navigator.clipboard.writeText(text);setCopyError(false);setCopied(true);setTimeout(()=>setCopied(false),1500)}catch{setCopied(false);setCopyError(true)}}
 function handleInstallKeyDown(event:KeyboardEvent<HTMLButtonElement>,index:number){const tabs=["pnpm","npm","yarn"] as const;let next=index;if(event.key==="ArrowRight")next=(index+1)%tabs.length;if(event.key==="ArrowLeft")next=(index+tabs.length-1)%tabs.length;if(event.key==="Home")next=0;if(event.key==="End")next=tabs.length-1;if(next===index)return;event.preventDefault();setInstallTab(tabs[next]);installTabsRef.current?.querySelector<HTMLButtonElement>(`[data-install-tab="${tabs[next]}"]`)?.focus()}
 return <main><span className="sr-only" aria-live="polite">{copied?"Copied":copyError?"Unable to copy. Please try again.":""}</span><Header/>
 <section id="demo" className="grid-bg border-b line"><div className="mx-auto grid min-h-[calc(100dvh-72px)] max-w-[1240px] items-center gap-10 px-5 py-10 lg:grid-cols-[.78fr_1.22fr] lg:px-8 lg:py-12"><div><p className="mono mb-6 text-[11px] uppercase tracking-[.2em] text-[var(--accent)]">Browser-native cryptography</p><h1 className="max-w-[620px] text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[64px]">Try post-quantum encryption.<br/><span className="text-[var(--muted)]">Right in your browser.</span></h1><p className="mt-7 max-w-[450px] text-base leading-7 text-[var(--muted)]">Generate keys, encrypt a message, decrypt it, and verify the result locally.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#demo" className="rounded-lg bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#0b0d0f] transition hover:bg-white active:scale-[.98]">Run the Demo</a><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="rounded-lg border px-5 py-3 text-sm line transition hover:border-[var(--accent)]">View on GitHub</a></div></div><Playground s={s} busy={busy} generate={generate} encrypt={encrypt} decrypt={decrypt} runComplete={runComplete} onMessage={value=>{executionSnapshot.current=null;d({type:"message",value})}} onAlgorithm={value=>{executionSnapshot.current=null;d({type:"algorithm",value})}}/></div></section>
 <TrustPanel />
 <section className="border-y bg-[#0f1215] py-24 line"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">The API stays small.</h2><p className="mt-4 max-w-[370px] text-sm leading-6 text-[var(--muted)]">A few readable calls connect the complete encryption flow.</p></div><div className="overflow-hidden rounded-xl border bg-[#0b0d0f] line"><div className="flex justify-between border-b px-4 py-3 line"><span className="mono text-[10px] text-[var(--faint)]">quickstart.ts</span><button onClick={()=>copy(code)} className="mono text-[11px] text-[var(--accent)]">{copied?"Copied":"Copy code"}</button></div><pre className="overflow-x-auto p-5 text-[12px] leading-7 text-[#c5d0da]"><code>{code}</code></pre></div></div></section>
 <section className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Real work, measured locally.</h2><p className="mt-3 text-sm text-[var(--muted)]">A timing trace from this browser session.</p><div className="mt-10 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-xl border bg-[var(--surface)] p-6 line"><p className="mono text-[10px] text-[var(--faint)]">TOTAL EXECUTION</p><p className="metric-value mt-5 text-5xl font-semibold tracking-[-.06em]">{total?<AnimatedNumber value={total} suffix=" ms"/>:"Waiting"}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Results vary by browser, device and workload.</p></div><div className="rounded-xl border bg-[var(--surface)] p-6 line">{[["Key generation",s.times.key,"Creates the post-quantum key pair"],["Encryption",s.times.encrypt,"Seals the message with the public key"],["Decryption",s.times.decrypt,"Recovers the message with the secret key"]].map(([label,value,desc])=><div key={label as string} className="border-b py-4 first:pt-0 last:border-0 line"><div className="flex justify-between text-sm"><span>{label}</span><span className="mono text-xs text-[var(--accent)]">{ms(value as number|null)}</span></div><div className="mt-3 h-1 bg-[#283038]"><div className="h-full bg-[var(--accent)] transition-all" style={{width:value?`${Math.max(5,(value as number/max)*100)}%`:"0%"}}/></div><p className="mt-2 text-xs text-[var(--muted)]">{desc}</p></div>)}</div></div></section>
 <section id="install" className="border-y bg-[#0f1215] py-24 line"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Install the SDK.</h2><p className="mt-4 text-sm text-[var(--muted)]">Add browser-ready post-quantum encryption to a TypeScript project.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-[var(--accent)]"><a href="https://jeloercc.github.io/pqc-sdk/" target="_blank" rel="noreferrer">View Documentation</a><a href="https://jeloercc.github.io/pqc-sdk/guide/quickstart" target="_blank" rel="noreferrer">Quick Start</a></div></div><div><div ref={installTabsRef} role="tablist" aria-label="Package manager" className="mb-3 flex gap-5 border-b line"><button id="install-tab-pnpm" role="tab" aria-selected={installTab==="pnpm"} aria-controls="install-panel-pnpm" tabIndex={installTab==="pnpm"?0:-1} data-install-tab="pnpm" onClick={()=>setInstallTab("pnpm")} onKeyDown={event=>handleInstallKeyDown(event,0)} className={`pb-3 text-xs ${installTab==="pnpm"?"border-b-2 border-[var(--accent)] text-[var(--text)]":"text-[var(--muted)]"}`}>pnpm</button><button id="install-tab-npm" role="tab" aria-selected={installTab==="npm"} aria-controls="install-panel-npm" tabIndex={installTab==="npm"?0:-1} data-install-tab="npm" onClick={()=>setInstallTab("npm")} onKeyDown={event=>handleInstallKeyDown(event,1)} className={`pb-3 text-xs ${installTab==="npm"?"border-b-2 border-[var(--accent)] text-[var(--text)]":"text-[var(--muted)]"}`}>npm</button><button id="install-tab-yarn" role="tab" aria-selected={installTab==="yarn"} aria-controls="install-panel-yarn" tabIndex={installTab==="yarn"?0:-1} data-install-tab="yarn" onClick={()=>setInstallTab("yarn")} onKeyDown={event=>handleInstallKeyDown(event,2)} className={`pb-3 text-xs ${installTab==="yarn"?"border-b-2 border-[var(--accent)] text-[var(--text)]":"text-[var(--muted)]"}`}>yarn</button></div>{(()=>{const command=installTab==="pnpm"?"pnpm add @pqc-sdk/core":installTab==="yarn"?"yarn add @pqc-sdk/core":"npm install @pqc-sdk/core";return <div id={`install-panel-${installTab}`} role="tabpanel" aria-labelledby={`install-tab-${installTab}`} className="mono flex justify-between rounded-lg border bg-[var(--surface)] px-4 py-4 text-xs line"><span><span className="mr-3 text-[var(--faint)]">$</span>{command}</span><button onClick={()=>copy(command)} className="text-[var(--accent)]">{copied?"Copied":"Copy"}</button></div>})()}</div></div></section>
 <section id="why-pqc" className="mx-auto grid max-w-[1240px] gap-10 px-5 py-24 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-32"><h2 className="max-w-[720px] text-4xl font-semibold leading-[1.05] tracking-[-.05em] sm:text-6xl">Encrypted traffic can be stored today and targeted later.</h2><p className="self-end border-l-2 border-[var(--accent)] pl-5 text-sm leading-7 text-[var(--muted)]">Post-quantum cryptography is designed to help protect against the risk of future large-scale quantum computers.</p></section>
 <section className="border-t bg-[var(--surface)] py-24 line"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><h2 className="text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Built in the open.</h2><p className="mt-5 max-w-[500px] text-sm leading-6 text-[var(--muted)]">Explore the implementation and install the package from its primary sources.</p><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="mt-7 inline-flex rounded-lg bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#0b0d0f]">View on GitHub</a></div><div className="grid gap-3 sm:grid-cols-2"><a href="https://github.com/jeloercc/pqc-sdk/blob/main/LICENSE" target="_blank" rel="noreferrer" className="rounded-lg border p-4 line"><span className="block text-sm">MIT License</span><span className="mono mt-2 block text-[10px] text-[var(--muted)]">License</span></a><a href="https://jeloercc.github.io/pqc-sdk/guide/quickstart" target="_blank" rel="noreferrer" className="rounded-lg border p-4 line"><span className="block text-sm">Documentation</span><span className="mono mt-2 block text-[10px] text-[var(--muted)]">Quick start</span></a><a href="https://jeloercc.github.io/pqc-sdk/api/" target="_blank" rel="noreferrer" className="rounded-lg border p-4 line"><span className="block text-sm">API Reference</span><span className="mono mt-2 block text-[10px] text-[var(--muted)]">API</span></a><a href="https://www.npmjs.com/package/@pqc-sdk/core" target="_blank" rel="noreferrer" className="rounded-lg border p-4 line"><span className="block text-sm">npm package</span><span className="mono mt-2 block text-[10px] text-[var(--muted)]">@pqc-sdk/core</span></a></div></div></section><footer className="mx-auto flex max-w-[1240px] flex-col gap-3 px-5 py-8 text-xs text-[var(--faint)] sm:flex-row sm:justify-between lg:px-8"><span className="mono">PQC SDK / Open source cryptography</span><span>MIT License. Keys stay in memory and leave with this page.</span></footer></main>
}
function Header(){return <header className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between border-b px-5 line lg:px-8"><a href="#" className="flex items-center gap-3 text-sm font-semibold"><span className="mono text-[var(--accent)]">[pqc]</span>PQC SDK</a><nav className="hidden gap-8 text-sm text-[var(--muted)] sm:flex"><a href="#demo">Demo</a><a href="#install">Install</a><a href="#why-pqc">Why PQC</a><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer">GitHub</a></nav><a href="#demo" className="rounded-lg border px-3 py-2 text-xs text-[var(--accent)] line">Run the Demo</a></header>}
function TrustPanel(){return <section className="border-b py-6 line"><div className="mx-auto grid max-w-[1240px] gap-4 px-5 sm:grid-cols-2 lg:grid-cols-4 lg:px-8"><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="border-l pl-4 text-sm line"><span className="block font-medium">Open Source</span><span className="mt-1 block text-xs text-[var(--muted)]">Repository</span></a><a href="https://github.com/jeloercc/pqc-sdk/blob/main/LICENSE" target="_blank" rel="noreferrer" className="border-l pl-4 text-sm line"><span className="block font-medium">MIT Licensed</span><span className="mt-1 block text-xs text-[var(--muted)]">License</span></a><a href="https://jeloercc.github.io/pqc-sdk/guide/quickstart" target="_blank" rel="noreferrer" className="border-l pl-4 text-sm line"><span className="block font-medium">Browser Native</span><span className="mt-1 block text-xs text-[var(--muted)]">Documentation</span></a><a href="https://www.npmjs.com/package/@pqc-sdk/core" target="_blank" rel="noreferrer" className="border-l pl-4 text-sm line"><span className="block font-medium">TypeScript First</span><span className="mt-1 block text-xs text-[var(--muted)]">Package</span></a></div></section>}
function Playground({s,busy,generate,encrypt,decrypt,runComplete,onMessage,onAlgorithm}:{s:State;busy:boolean;generate:()=>void;encrypt:()=>void;decrypt:()=>void;runComplete:()=>void;onMessage:(value:string)=>void;onAlgorithm:(value:Algorithm)=>void}){return <div aria-busy={busy} className="rounded-xl border bg-[var(--surface)] p-5 shadow-2xl shadow-black/20 line"><div className="flex justify-between border-b pb-4 line"><span className="mono text-[10px] text-[var(--faint)]">pqc playground</span><span role="status" aria-live="polite" className={`mono text-[10px] ${s.verified?"text-[var(--success)]":"text-[var(--accent)]"}`}>{busy?s.phase.toUpperCase():s.verified?"VERIFIED":"READY"}</span></div><label className="mono mt-5 block text-[11px] uppercase tracking-[.15em] text-[var(--muted)]" htmlFor="hero-message">Message</label><textarea id="hero-message" maxLength={2000} value={s.message} disabled={busy} onChange={e=>onMessage(e.target.value)} className="mt-3 min-h-[92px] w-full resize-y rounded-lg border bg-[#0d1012] p-3 text-sm leading-6 outline-none line focus:border-[var(--accent)] disabled:cursor-not-allowed disabled:opacity-60"/><div className="mt-4 grid gap-2 sm:grid-cols-2"><Algo active={s.algorithm==="ml-kem-768"} onClick={()=>onAlgorithm("ml-kem-768")} title="ML-KEM-768" detail="SDK default" disabled={busy}/><Algo active={s.algorithm==="x-wing"} onClick={()=>onAlgorithm("x-wing")} title="X-Wing hybrid" detail="Advanced mode" disabled={busy}/></div><button onClick={runComplete} disabled={busy} className="mt-4 w-full rounded-lg bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-[#0b0d0f] transition hover:bg-white active:scale-[.98] disabled:cursor-wait disabled:opacity-60">{busy?"Processing...":"Run complete demo"}</button><div className="mt-4 space-y-3"><Mini title="Generate Keys" operation="generating" active={s.phase==="generating"} time={s.times.key} done={!!s.pair} run={generate} disabled={busy}/><Mini title="Encrypt Message" operation="encrypting" active={s.phase==="encrypting"} time={s.times.encrypt} done={!!s.ciphertext} run={encrypt} disabled={busy||!s.pair}/><Mini title="Decrypt Message" operation="decrypting" active={s.phase==="decrypting"} time={s.times.decrypt} done={!!s.plaintext} run={decrypt} disabled={busy||!s.ciphertext}/></div>{s.error&&<p role="alert" aria-live="assertive" className="mt-4 rounded-lg border border-[var(--danger)]/40 p-3 text-xs text-[var(--danger)]">{s.error}</p>}{s.verified&&<><p className="success-pop mt-4 rounded-lg border bg-[#8bd6ae0d] p-3 text-xs text-[var(--success)] line">✓ Messages match</p><div className="mt-4 grid grid-cols-3 gap-3 border-t pt-4 line"><Metric label="Keys" value={s.times.key}/><Metric label="Encrypt" value={s.times.encrypt}/><Metric label="Decrypt" value={s.times.decrypt}/></div><ExecutionDetails s={s}/></>}<div className="mono mt-5 text-[10px] text-[var(--faint)]">NO SERVER REQUESTS / EPHEMERAL KEYS</div></div>}
function Mini({title,operation,time,active,done,run,disabled}:{title:string;operation:Phase;time:number|null;active:boolean;done:boolean;run:()=>void;disabled:boolean}){const verb=operation==="generating"?"Generate":operation==="encrypting"?"Encrypt":"Decrypt";const present=operation==="generating"?"Generating":operation==="encrypting"?"Encrypting":"Decrypting";const past=operation==="generating"?"Generated":operation==="encrypting"?"Encrypted":"Decrypted";return <div className={`operation-row flex items-center gap-3 rounded-lg border p-4 line ${done?"operation-done":""}`}><span className={`mono text-[10px] ${done?"text-[var(--success)]":active?"text-[var(--accent)]":"text-[var(--faint)]"}`}>{done?"OK":active?"...":"--"}</span><span className="flex-1 text-sm"><span className="block">{active?`${present}...`:title}</span>{done&&<span className="mono mt-1 block text-[10px] text-[var(--success)]">{past} in {ms(time)}</span>}</span><button onClick={run} disabled={disabled} className="rounded-md border px-3 py-2 text-xs transition hover:border-[var(--accent)] active:scale-[.98]">{done?"Run again":verb}</button></div>}
function Algo({active,onClick,title,detail,disabled}:{active:boolean;onClick:()=>void;title:string;detail:string;disabled:boolean}){return <button type="button" aria-pressed={active} disabled={disabled} onClick={onClick} className={`rounded-lg border p-3 text-left line disabled:cursor-not-allowed disabled:opacity-60 ${active?"border-[var(--accent)] bg-[#78b8ff12]":""}`}><span className="block text-xs">{title}</span><span className="mono mt-1 block text-[10px] text-[var(--muted)]">{detail}</span></button>}
function AnimatedNumber({value,suffix=""}:{value:number;suffix?:string}){const [display,setDisplay]=useState(0);useEffect(()=>{if(window.matchMedia("(prefers-reduced-motion: reduce)").matches){setDisplay(value);return}const start=performance.now();const duration=500;let frame=0;const tick=(now:number)=>{const progress=Math.min((now-start)/duration,1);setDisplay(value*progress);if(progress<1)frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[value]);return <>{display.toFixed(1)}{suffix}</>}
function Metric({label,value}:{label:string;value:number|null}){return <div><p className="mono text-[10px] text-[var(--faint)]">{label}</p><p className="metric-value mt-2 text-xs">{value===null?"Waiting":<AnimatedNumber value={value} suffix=" ms"/>}</p></div>}
function ExecutionDetails({s}:{s:State}){const [detailsOpen,setDetailsOpen]=useState(false);const [artifactsOpen,setArtifactsOpen]=useState(false);useEffect(()=>{if(s.verified){setDetailsOpen(true);setArtifactsOpen(true)}},[s.verified]);if(!s.pair||!s.ciphertext)return null;return <><details open={detailsOpen} onToggle={event=>setDetailsOpen(event.currentTarget.open)} className="details-panel mt-4 rounded-lg border line"><summary className="cursor-pointer list-none px-4 py-3 text-sm font-medium">Execution details <span className="mono float-right text-[10px] text-[var(--faint)]">metadata only</span></summary><div className="grid gap-x-5 gap-y-4 border-t px-4 py-4 sm:grid-cols-2 line"><Detail label="Algorithm" value={s.algorithm}/><Detail label="Public key size" value={`${s.pair.publicKey.bytes.byteLength} bytes`}/><Detail label="Secret key size" value={`${s.pair.secretKey.bytes.byteLength} bytes`}/><Detail label="Ciphertext size" value={`${s.ciphertext.byteLength} bytes`}/><Detail label="Plaintext size" value={s.plaintextSize===null?"Waiting":`${s.plaintextSize} bytes`}/><Detail label="Verification status" value={s.verified?"Messages match":"Not verified"} success={s.verified}/></div></details><details open={artifactsOpen} onToggle={event=>setArtifactsOpen(event.currentTarget.open)} className="details-panel mt-3 rounded-lg border line"><summary className="cursor-pointer list-none px-4 py-3 text-sm font-medium">Cryptographic artifacts <span className="mono float-right text-[10px] text-[var(--faint)]">previews only</span></summary><div className="space-y-4 border-t px-4 py-4 line"><Detail label="Ciphertext preview" value={hexPreview(s.ciphertext)}/><Detail label="Plaintext preview" value={s.plaintext?preview(s.plaintext):"Waiting"}/><Detail label="Verification result" value={s.verified?"✓ Messages Match":"Not verified"} success={s.verified}/></div></details><Trace events={s.trace}/></>}
function Detail({label,value,success}:{label:string;value:string;success?:boolean}){return <div className="min-w-0"><p className="mono text-[10px] text-[var(--faint)]">{label}</p><p className={`mt-1 truncate text-xs ${success?"text-[var(--success)]":""}`}>{value}</p></div>}
function preview(value:string){const compact=value.replace(/\s+/g," ").trim();return compact.length>48?`${compact.slice(0,48)}…`:compact}
function hexPreview(value:Uint8Array){const bytes=Array.from(value).slice(0,18).map(byte=>byte.toString(16).padStart(2,"0")).join("");return `${bytes}...`}
function Trace({events}:{events:TraceEvent[]}){return <div className="trace-panel mt-4 border-t pt-4 line"><div className="mb-3 flex items-center justify-between"><span className="mono text-[10px] uppercase tracking-[.15em] text-[var(--muted)]">Execution trace</span><span className="mono text-[10px] text-[var(--faint)]">{events.length} events</span></div><div className="space-y-3">{events.map((event,index)=><div key={`${event.label}-${index}`} className="trace-event flex gap-3"><span className={`mt-1 h-2 w-2 shrink-0 rounded-full ${event.tone==="success"?"bg-[var(--success)]":"bg-[var(--accent)]"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap justify-between gap-x-3 text-xs"><span>{event.label}</span><span className="mono text-[10px] text-[var(--accent)]">[{event.time.toFixed(1)} ms]</span></div><p className="mt-1 text-[10px] text-[var(--muted)]">{event.detail}</p></div></div>)}</div></div>}
