"use client";
import { useMemo, useReducer, useState } from "react";
import type { KeyPair } from "@pqc-sdk/core";

type Algorithm = "ml-kem-768" | "x-wing";
type Phase = "idle" | "generating" | "encrypting" | "decrypting";
type KemPair = KeyPair<"ml-kem-768" | "x-wing">;
type State = { message:string; algorithm:Algorithm; pair:KemPair|null; ciphertext:Uint8Array|null; plaintext:string|null; times:{key:number|null;encrypt:number|null;decrypt:number|null}; phase:Phase; error:string|null };
type Action = {type:"message";value:string}|{type:"algorithm";value:Algorithm}|{type:"phase";value:Phase}|{type:"keys";pair:State["pair"];time:number}|{type:"encrypted";value:Uint8Array;time:number}|{type:"decrypted";value:string;time:number}|{type:"error";value:string}|{type:"reset"};
const initial:State={message:"This message should remain private.",algorithm:"ml-kem-768",pair:null,ciphertext:null,plaintext:null,times:{key:null,encrypt:null,decrypt:null},phase:"idle",error:null};
function reducer(s:State,a:Action):State{switch(a.type){case"message":return{...s,message:a.value,pair:null,ciphertext:null,plaintext:null,times:{key:null,encrypt:null,decrypt:null},error:null};case"algorithm":return{...initial, message:s.message,algorithm:a.value};case"phase":return{...s,phase:a.value,error:null};case"keys":return{...s,pair:a.pair,phase:"idle",ciphertext:null,plaintext:null,times:{key:a.time,encrypt:null,decrypt:null},error:null};case"encrypted":return{...s,ciphertext:a.value,phase:"idle",plaintext:null,times:{...s.times,encrypt:a.time,decrypt:null},error:null};case"decrypted":return{...s,plaintext:a.value,phase:"idle",times:{...s.times,decrypt:a.time},error:null};case"error":return{...s,phase:"idle",error:a.value};case"reset":return initial}}
const ms=(n:number|null)=>n===null?"Waiting":`${n.toFixed(1)} ms`;
const size=(x:Uint8Array|string|{bytes:Uint8Array})=>typeof x==="string"?new TextEncoder().encode(x).byteLength:"bytes" in x?x.bytes.byteLength:x.byteLength;
const preview=(x:Uint8Array)=>Array.from(x.slice(0,28)).map(v=>v.toString(16).padStart(2,"0")).join("")+"...";
const code=`import { pqc } from '@pqc-sdk/core';

const pair = await pqc.keys.generate();

const ciphertext = await pqc.encrypt(
  message,
  pair.publicKey
);

const plaintext = await pqc.decrypt(
  ciphertext,
  pair.secretKey
);`;
async function generatePair(pqc: typeof import("@pqc-sdk/core").pqc, algorithm: Algorithm): Promise<KemPair> {
  return algorithm === "x-wing" ? pqc.keys.generate({ algorithm: "x-wing" }) : pqc.keys.generate({ algorithm: "ml-kem-768" });
}

export function Demo(){
 const [s,d]=useReducer(reducer,initial); const [copied,setCopied]=useState(false);
 const busy=s.phase!=="idle"; const total=useMemo(()=>Object.values(s.times).reduce<number>((a,b)=>a+(b??0),0),[s.times]); const max=Math.max(...Object.values(s.times).map(x=>x??0),1);
 async function generate(){d({type:"phase",value:"generating"});try{const {pqc}=await import("@pqc-sdk/core");const t=performance.now();const pair=await generatePair(pqc,s.algorithm);d({type:"keys",pair,time:performance.now()-t})}catch{d({type:"error",value:"The cryptographic module could not initialize. Try a current browser and run again."})}}
 async function encrypt(){if(!s.pair||!s.message.trim())return d({type:"error",value:"Enter a message before encrypting."});d({type:"phase",value:"encrypting"});try{const {pqc}=await import("@pqc-sdk/core");const t=performance.now();const value=await pqc.encrypt(s.message,s.pair.publicKey);d({type:"encrypted",value,time:performance.now()-t})}catch{d({type:"error",value:"Encryption failed. Reset the demo and try again."})}}
 async function decrypt(){if(!s.pair||!s.ciphertext)return;d({type:"phase",value:"decrypting"});try{const {pqc}=await import("@pqc-sdk/core");const t=performance.now();const value=await pqc.decrypt(s.ciphertext,s.pair.secretKey);d({type:"decrypted",value:new TextDecoder().decode(value),time:performance.now()-t})}catch{d({type:"error",value:"Decryption failed. Reset the demo and try again."})}}
 async function runComplete(){if(!s.message.trim())return d({type:"error",value:"Enter a message before running the demo."});d({type:"phase",value:"generating"});try{const {pqc}=await import("@pqc-sdk/core");const keyStart=performance.now();const pair=await generatePair(pqc,s.algorithm);d({type:"keys",pair,time:performance.now()-keyStart});d({type:"phase",value:"encrypting"});const encryptStart=performance.now();const ciphertext=await pqc.encrypt(s.message,pair.publicKey);d({type:"encrypted",value:ciphertext,time:performance.now()-encryptStart});d({type:"phase",value:"decrypting"});const decryptStart=performance.now();const value=await pqc.decrypt(ciphertext,pair.secretKey);d({type:"decrypted",value:new TextDecoder().decode(value),time:performance.now()-decryptStart})}catch{d({type:"error",value:"The demo could not complete. Reset it and try again."})}}
 async function copy(){await navigator.clipboard?.writeText(code);setCopied(true);setTimeout(()=>setCopied(false),1500)}
 return <main><Header/>
 <section className="grid-bg border-b line"><div className="mx-auto grid min-h-[calc(100dvh-72px)] max-w-[1240px] items-center gap-12 px-5 py-12 lg:grid-cols-[.88fr_1.12fr] lg:px-8 lg:py-16"><div><p className="mono mb-6 text-[11px] uppercase tracking-[.2em] text-[var(--accent)]">Browser-native cryptography</p><h1 className="max-w-[620px] text-5xl font-semibold leading-[.98] tracking-[-.06em] sm:text-6xl lg:text-[68px]">Try post-quantum encryption.<br/><span className="text-[var(--muted)]">Right in your browser.</span></h1><p className="mt-7 max-w-[450px] text-base leading-7 text-[var(--muted)]">Generate keys, encrypt a message, decrypt it, and inspect the real timings locally.</p><div className="mt-9 flex flex-wrap gap-3"><a href="#demo" className="rounded-lg bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#0b0d0f] transition hover:bg-white active:scale-[.98]">Run the Demo</a><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="rounded-lg border px-5 py-3 text-sm line transition hover:border-[var(--accent)]">View Source</a></div><div className="mono mt-8 flex flex-wrap gap-x-5 gap-y-2 text-[10px] text-[var(--faint)]"><span>NO SERVER REQUESTS</span><span>MIT LICENSED</span><span>TYPESCRIPT SDK</span></div></div><Playground s={s} busy={busy} generate={generate} encrypt={encrypt} decrypt={decrypt} runComplete={runComplete}/></div></section>
 <section className="border-b px-5 py-6 line"><div className="mx-auto flex max-w-[1240px] flex-col gap-3 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><p className="text-sm font-medium">Install in one command.</p><p className="mt-1 text-xs text-[var(--muted)]">Start with the browser-ready TypeScript package.</p></div><div className="flex w-full items-center justify-between rounded-lg border bg-[var(--surface)] px-4 py-3 sm:w-auto sm:min-w-[390px] line"><code className="mono text-xs">npm install @pqc-sdk/core</code><button onClick={()=>navigator.clipboard?.writeText("npm install @pqc-sdk/core")} className="mono ml-4 text-[11px] text-[var(--accent)]">Copy</button></div></div></section>
 <section id="demo" className="mx-auto max-w-[1240px] scroll-mt-6 px-5 py-24 lg:px-8 lg:py-32"><div className="mb-10 flex items-end justify-between"><div><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">PQC Playground</h2><p className="mt-3 text-sm text-[var(--muted)]">Run the complete encryption flow locally and inspect each operation as it finishes.</p></div>{(s.pair||s.error)&&<button onClick={()=>d({type:"reset"})} className="mono text-[11px] text-[var(--muted)] underline hover:text-white">Reset demo</button>}</div><div className="grid overflow-hidden rounded-xl border bg-[var(--surface)] line lg:grid-cols-[.9fr_1.1fr]"><div className="border-b p-5 line sm:p-7 lg:border-b-0 lg:border-r"><label className="mono text-[11px] uppercase tracking-[.15em] text-[var(--muted)]" htmlFor="message">Message</label><textarea id="message" maxLength={2000} value={s.message} onChange={e=>d({type:"message",value:e.target.value})} className="mt-3 min-h-[145px] w-full resize-y rounded-lg border bg-[#0d1012] p-4 text-sm leading-6 outline-none line focus:border-[var(--accent)]"/><div className="mono mt-2 text-right text-[10px] text-[var(--faint)]">{s.message.length} / 2,000</div><div className="mt-7"><span className="mono text-[11px] uppercase tracking-[.15em] text-[var(--muted)]">Algorithm</span><div className="mt-3 grid gap-2 sm:grid-cols-2"><Algo active={s.algorithm==="ml-kem-768"} onClick={()=>d({type:"algorithm",value:"ml-kem-768"})} title="ML-KEM-768" detail="SDK default"/><Algo active={s.algorithm==="x-wing"} onClick={()=>d({type:"algorithm",value:"x-wing"})} title="X-Wing hybrid" detail="Advanced mode"/></div></div><div className="mt-8 space-y-3"><Op n="01" title="Generate Keys" detail="Create a post-quantum key pair" done={!!s.pair} run={generate} disabled={busy}/><Op n="02" title="Encrypt Message" detail="Seal the message with the public key" done={!!s.ciphertext} run={encrypt} disabled={busy||!s.pair||!s.message.trim()}/><Op n="03" title="Decrypt Message" detail="Recover it with the secret key" done={!!s.plaintext} run={decrypt} disabled={busy||!s.ciphertext}/></div>{s.error&&<p role="alert" className="mt-5 rounded-lg border border-[var(--danger)]/40 p-3 text-xs text-[var(--danger)]">{s.error}</p>}</div><Output s={s} total={total} max={max}/></div></section>
 <section className="border-y bg-[#0f1215] py-24 line"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">The API stays small.</h2><p className="mt-4 max-w-[370px] text-sm leading-6 text-[var(--muted)]">A few readable calls connect the complete encryption flow.</p></div><div className="overflow-hidden rounded-xl border bg-[#0b0d0f] line"><div className="flex justify-between border-b px-4 py-3 line"><span className="mono text-[10px] text-[var(--faint)]">quickstart.ts</span><button onClick={copy} className="mono text-[11px] text-[var(--accent)]">{copied?"Copied":"Copy code"}</button></div><pre className="overflow-x-auto p-5 text-[12px] leading-7 text-[#c5d0da]"><code>{code}</code></pre></div></div></section>
 <section className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8 lg:py-32"><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Real work, measured locally.</h2><p className="mt-3 text-sm text-[var(--muted)]">A timing trace from this browser session.</p><div className="mt-10 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><div className="rounded-xl border bg-[var(--surface)] p-6 line"><p className="mono text-[10px] text-[var(--faint)]">TOTAL EXECUTION</p><p className="mt-5 text-5xl font-semibold tracking-[-.06em]">{total?`${total.toFixed(1)} ms`:"Waiting"}</p><p className="mt-3 text-sm leading-6 text-[var(--muted)]">Results vary by browser, device and workload.</p></div><div className="rounded-xl border bg-[var(--surface)] p-6 line">{[["Key generation",s.times.key,"Creates the post-quantum key pair"],["Encryption",s.times.encrypt,"Seals the message with the public key"],["Decryption",s.times.decrypt,"Recovers the message with the secret key"]].map(([label,value,desc])=><div key={label as string} className="border-b py-4 first:pt-0 last:border-0 line"><div className="flex justify-between text-sm"><span>{label}</span><span className="mono text-xs text-[var(--accent)]">{ms(value as number|null)}</span></div><div className="mt-3 h-1 bg-[#283038]"><div className="h-full bg-[var(--accent)] transition-all" style={{width:value?`${Math.max(5,(value as number/max)*100)}%`:"0%"}}/></div><p className="mt-2 text-xs text-[var(--muted)]">{desc}</p></div>)}</div></div></section>
 <section id="install" className="border-y bg-[#0f1215] py-24 line"><div className="mx-auto grid max-w-[1240px] gap-10 px-5 lg:grid-cols-[.75fr_1.25fr] lg:px-8"><div><h2 className="text-3xl font-semibold tracking-[-.04em] sm:text-4xl">Install the SDK.</h2><p className="mt-4 text-sm text-[var(--muted)]">Add browser-ready post-quantum encryption to a TypeScript project.</p><div className="mt-7 flex flex-wrap gap-5 text-sm text-[var(--accent)]"><a href="https://jeloercc.github.io/pqc-sdk/guide/quickstart" target="_blank" rel="noreferrer">Documentation</a><a href="https://jeloercc.github.io/pqc-sdk/api/" target="_blank" rel="noreferrer">API Reference</a><a href="https://jeloercc.github.io/pqc-sdk/guide/quickstart" target="_blank" rel="noreferrer">Quick Start</a></div></div><div className="space-y-2">{["pnpm add @pqc-sdk/core","npm install @pqc-sdk/core","yarn add @pqc-sdk/core"].map(x=><div key={x} className="mono flex justify-between rounded-lg border bg-[var(--surface)] px-4 py-4 text-xs line"><span><span className="mr-3 text-[var(--faint)]">$</span>{x}</span><button onClick={()=>navigator.clipboard?.writeText(x)} className="text-[var(--accent)]">Copy</button></div>)}</div></div></section>
 <section id="why-pqc" className="mx-auto grid max-w-[1240px] gap-10 px-5 py-24 lg:grid-cols-[1.2fr_.8fr] lg:px-8 lg:py-32"><h2 className="max-w-[720px] text-4xl font-semibold leading-[1.05] tracking-[-.05em] sm:text-6xl">Encrypted traffic can be stored today and targeted later.</h2><p className="self-end border-l-2 border-[var(--accent)] pl-5 text-sm leading-7 text-[var(--muted)]">Post-quantum cryptography is designed to help protect against the risk of future large-scale quantum computers.</p></section>
 <section className="border-t bg-[var(--surface)] py-24 line"><div className="mx-auto flex max-w-[1240px] flex-col justify-between gap-10 px-5 lg:flex-row lg:items-end lg:px-8"><div><h2 className="text-4xl font-semibold tracking-[-.05em] sm:text-6xl">Built in the open.</h2><p className="mt-5 max-w-[500px] text-sm leading-6 text-[var(--muted)]">Explore the implementation and help improve post-quantum tooling for JavaScript and TypeScript.</p></div><div className="flex flex-wrap gap-3"><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="rounded-lg bg-[var(--accent)] px-5 py-3 text-sm font-semibold text-[#0b0d0f]">Star on GitHub</a><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer" className="rounded-lg border px-5 py-3 text-sm line">View the Source</a></div></div></section><footer className="mx-auto flex max-w-[1240px] flex-col gap-3 px-5 py-8 text-xs text-[var(--faint)] sm:flex-row sm:justify-between lg:px-8"><span className="mono">PQC SDK / Open source cryptography</span><span>MIT License. Keys stay in memory and leave with this page.</span></footer></main>
}
function Header(){return <header className="mx-auto flex h-[72px] max-w-[1240px] items-center justify-between border-b px-5 line lg:px-8"><a href="#" className="flex items-center gap-3 text-sm font-semibold"><span className="mono text-[var(--accent)]">[pqc]</span>PQC SDK</a><nav className="hidden gap-8 text-sm text-[var(--muted)] sm:flex"><a href="#demo">Demo</a><a href="#install">Install</a><a href="#why-pqc">Why PQC</a><a href="https://github.com/jeloercc/pqc-sdk" target="_blank" rel="noreferrer">GitHub</a></nav><a href="#demo" className="rounded-lg border px-3 py-2 text-xs text-[var(--accent)] line">Run the Demo</a></header>}
function Playground({s,busy,generate,encrypt,decrypt,runComplete}:{s:State;busy:boolean;generate:()=>void;encrypt:()=>void;decrypt:()=>void;runComplete:()=>void}){return <div className="rounded-xl border bg-[var(--surface)] p-5 shadow-2xl shadow-black/20 line"><div className="flex justify-between border-b pb-4 line"><span className="mono text-[10px] text-[var(--faint)]">pqc playground</span><span className={`mono text-[10px] ${s.plaintext?"text-[var(--success)]":"text-[var(--accent)]"}`}>{busy?s.phase.toUpperCase():s.plaintext?"COMPLETE":"READY"}</span></div><button onClick={runComplete} disabled={busy} className="mt-5 w-full rounded-lg bg-[var(--accent)] px-4 py-3 text-sm font-semibold text-[#0b0d0f] transition hover:bg-white active:scale-[.98] disabled:cursor-wait disabled:opacity-60">{busy?"Running...":"Run complete demo"}</button><div className="mt-4 space-y-3"><Mini title="Generate Keys" done={!!s.pair} run={generate} disabled={busy}/><Mini title="Encrypt Message" done={!!s.ciphertext} run={encrypt} disabled={busy||!s.pair}/><Mini title="Decrypt Message" done={!!s.plaintext} run={decrypt} disabled={busy||!s.ciphertext}/></div><div className="mono mt-5 text-[10px] text-[var(--faint)]">NO SERVER REQUESTS / EPHEMERAL KEYS</div></div>}
function Mini({title,done,run,disabled}:{title:string;done:boolean;run:()=>void;disabled:boolean}){return <div className="flex items-center gap-3 rounded-lg border p-4 line"><span className={`mono text-[10px] ${done?"text-[var(--success)]":"text-[var(--faint)]"}`}>{done?"OK":"--"}</span><span className="flex-1 text-sm">{title}</span><button onClick={run} disabled={disabled} className="rounded-md border px-3 py-2 text-[11px] line disabled:opacity-30">{done?"Done":"Run"}</button></div>}
function Algo({active,onClick,title,detail}:{active:boolean;onClick:()=>void;title:string;detail:string}){return <button onClick={onClick} className={`rounded-lg border p-3 text-left line ${active?"border-[var(--accent)] bg-[#78b8ff12]":""}`}><span className="block text-xs">{title}</span><span className="mono mt-1 block text-[10px] text-[var(--muted)]">{detail}</span></button>}
function Op({n,title,detail,done,run,disabled}:{n:string;title:string;detail:string;done:boolean;run:()=>void;disabled:boolean}){return <div className="flex items-center gap-3 border-b pb-3 line"><span className="mono w-5 text-[10px] text-[var(--faint)]">{done?"OK":n}</span><div className="flex-1"><p className="text-xs">{title}</p><p className="text-[10px] text-[var(--muted)]">{done?"Operation complete":detail}</p></div><button onClick={run} disabled={disabled} className="mono rounded border px-2 py-1.5 text-[10px] text-[var(--accent)] line disabled:opacity-30">{done?"Done":"Run"}</button></div>}
function Output({s,total,max}:{s:State;total:number;max:number}){return <div className="p-5 sm:p-7"><div className="flex justify-between"><h3 className="text-sm">Execution output</h3><span className="mono text-[10px] text-[var(--faint)]">{total?`${total.toFixed(1)} ms total`:"No run yet"}</span></div>{!s.pair?<div className="flex min-h-[370px] items-center justify-center text-center"><div><div className="mx-auto mb-5 h-12 w-12 rounded-full border border-dashed border-[var(--accent)]/50"/><p className="text-sm text-[var(--muted)]">Generate a key pair to begin.</p><p className="mt-2 text-xs text-[var(--faint)]">Your message and keys stay in this browser.</p></div></div>:<div className="mt-7 space-y-6"><div><div className="mb-4 text-xs font-medium">Keys generated</div><div className="grid grid-cols-2 gap-5"><Metric label="Algorithm" value={s.algorithm==="x-wing"?"X-Wing":"ML-KEM-768"}/><Metric label="Generation" value={ms(s.times.key)}/><Metric label="Public key" value={`${size(s.pair.publicKey).toLocaleString()} bytes`}/><Metric label="Secret key" value={`${size(s.pair.secretKey).toLocaleString()} bytes`}/></div></div>{s.ciphertext&&<div className="border-t pt-5 line"><div className="flex justify-between text-xs"><span>Encrypted message</span><span className="mono text-[var(--accent)]">{size(s.ciphertext).toLocaleString()} bytes / {ms(s.times.encrypt)}</span></div><p className="mono mt-3 overflow-hidden text-ellipsis whitespace-nowrap rounded bg-[#0d1012] p-3 text-[10px] text-[var(--faint)]">{preview(s.ciphertext)}</p></div>}{s.plaintext&&<div className="border-t pt-5 line"><div className="mb-3 text-xs">Decrypted message</div><p className="rounded-lg border bg-[#8bd6ae0d] p-4 text-sm line">{s.plaintext}</p><div className="mt-3 flex justify-between text-xs text-[var(--success)]"><span>Decryption successful. Messages match.</span><span className="mono">{ms(s.times.decrypt)}</span></div></div>}</div>}</div>}
function Metric({label,value}:{label:string;value:string}){return <div><p className="mono text-[10px] text-[var(--faint)]">{label}</p><p className="mt-2 text-xs">{value}</p></div>}
